import {
  Heart,
  Brain,
  Bone,
  Eye,
  Ear,
  Wind,
  Cross,
  Thermometer,
  Pill,
  Zap,
  Shield,
  Activity,
  User,
  Baby,
  Stethoscope,
  HeartHandshake,
  CircleDot,
  Sun,
  Moon,
  HeartPulse,
  UtensilsCrossed,
  Biohazard,
  BrainCircuit,
  Droplet,
  Droplets,
  Settings,
  Radiation,
  Syringe,
  GaugeCircle,
  Scale,
  Apple,
  Dumbbell,
  VenusAndMars,
  Egg,
  GraduationCap,
  Plane,
  CigaretteOff,
  BedDouble,
  Bed,
  ShieldCheck,
  HeartCrack,
  Scale3d,
  Video,
  MonitorCheck,
  BriefcaseMedical,
  Leaf,
  SearchCheck,
} from "lucide-react";

export interface HealthCategory {
  name: string;
  icon: React.ComponentType<{ className?: string }>; // Lucide React icon component
}

export const HEALTH_CATEGORIES: HealthCategory[] = [
  { name: "Cold & Flu", icon: Thermometer },
  { name: "Headaches", icon: Brain },
  { name: "Back Pain", icon: Bone },
  { name: "Skin Issues", icon: Sun },
  { name: "Stomach Problems", icon: Cross },
  { name: "Eye Problems", icon: Eye },
  { name: "Ear Infections", icon: Ear },
  { name: "Chest Pain", icon: Heart },
  { name: "Mental Health", icon: HeartHandshake },
  { name: "Allergies", icon: Shield },
  { name: "Sleep Issues", icon: Moon },
  { name: "Respiratory", icon: Wind },
  { name: "Joint Pain", icon: Bone },
  { name: "Diabetes Care", icon: Activity },
  { name: "Women's Health", icon: User },
  { name: "Men's Health", icon: Stethoscope },
  { name: "Pediatric Care", icon: Baby },
  { name: "Urgent Care", icon: Zap },
  { name: "Medication Review", icon: Pill },
  { name: "General Checkup", icon: CircleDot },
  { name: "Heart Health", icon: HeartPulse },
  { name: "Digestive Health", icon: UtensilsCrossed },
  { name: "Infectious Diseases", icon: Biohazard },
  { name: "Neurological Disorders", icon: BrainCircuit },
  { name: "Kidney & Urinary Health", icon: Droplet },
  { name: "Liver Care", icon: Droplets },
  { name: "Thyroid & Hormones", icon: Settings },
  { name: "Cancer Care", icon: Radiation },
  { name: "Immunization", icon: Syringe },
  { name: "Blood Pressure", icon: GaugeCircle },
  { name: "Cholesterol Management", icon: Scale },
  { name: "Nutrition & Diet", icon: Apple },
  { name: "Physical Therapy", icon: Dumbbell },
  { name: "Sexual Health", icon: VenusAndMars },
  { name: "Reproductive Health", icon: Egg },
  { name: "Geriatric Care", icon: User },
  { name: "Adolescent Health", icon: GraduationCap },
  { name: "Travel Medicine", icon: Plane },
  { name: "Addiction Support", icon: CigaretteOff },
  { name: "Post-Surgery Recovery", icon: BedDouble },
  { name: "Sleep Apnea", icon: Bed },
  { name: "Autoimmune Conditions", icon: ShieldCheck },
  { name: "Fitness & Preventive Care", icon: HeartCrack },
  { name: "Weight Management", icon: Scale3d },
  { name: "Telehealth Services", icon: Video },
  { name: "Home Health Monitoring", icon: MonitorCheck },
  { name: "Occupational Health", icon: BriefcaseMedical },
  { name: "Environmental Allergies", icon: Leaf },
  { name: "Pain Management", icon: Syringe },
  { name: "Rare Diseases", icon: SearchCheck },
];
